name: docker build

env:
    ZANO_REF: 2.0.1.367
    BUILD_WIDTH: 16

on:
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: "build target: zano-runner"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ env.ZANO_REF }}
          tags: zano:${{ env.ZANO_REF }}-latest
          target: zano-runner
          provenance: mode=max
          sbom: true

      - name: "build target: zanod-distroless"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ env.ZANO_REF }}
          tags: zanod-distroless:${{ env.ZANO_REF }}-latest
          target: zanod-distroless
          provenance: mode=max
          sbom: true

      - name: "build target: simplewallet-distroless"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ env.ZANO_REF }}
          tags: simplewallet-distroless:${{ env.ZANO_REF }}-latest
          target: simplewallet-distroless
          provenance: mode=max
          sbom: true