name: docker build

env:
    BUILD_WIDTH: 8

on:
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    name: docker build
    strategy:
      matrix:
        zano-ref: [2.1.4.396, 2.1.5.397, master]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Set SHA_SHORT for commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "build target: zano-runner"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ matrix.zano-ref }}
          tags: ${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-zano-runner,${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-zano-runner-${{ steps.vars.outputs.sha_short }}
          target: zano-runner
          # provenance: mode=max
          # sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "simple test: zano-runner"
        run: |
          docker run --rm ${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-zano-runner-${{ steps.vars.outputs.sha_short }} --version

      - name: "build target: zanod-distroless"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ matrix.zano-ref }}
          tags: ${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-zanod-distroless,${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-zanod-distroless-${{ steps.vars.outputs.sha_short }}
          target: zanod-distroless
          # provenance: mode=max
          # sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "simple test: zanod-distroless"
        run: |
          docker run --rm ${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-zanod-distroless-${{ steps.vars.outputs.sha_short }} --version

      - name: "build target: simplewallet-distroless"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ matrix.zano-ref }}
          tags: ${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-simplewallet-distroless,${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-simplewallet-distroless-${{ steps.vars.outputs.sha_short }}
          target: simplewallet-distroless
          # provenance: mode=max
          # sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "simple test: zanod-distroless"
        run: |
          docker run --rm ${{ vars.DOCKERHUB_REPO }}:${{ matrix.zano-ref }}-simplewallet-distroless-${{ steps.vars.outputs.sha_short }} --version

  # TESTNET #####################################################################

  testnet-docker-build:
    name: docker build (testnet)
    strategy:
      matrix:
        zano-ref: [develop, master]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup buildx (testnet)
        uses: docker/setup-buildx-action@v3

      - name: Set SHA_SHORT for commit (testnet)
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "build target: zano-runner (testnet)"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ matrix.zano-ref }}
            ZANO_CMAKE_ARGS="-D TESTNET=TRUE"
          tags: ${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-zano-runner,${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-zano-runner-${{ steps.vars.outputs.sha_short }}
          target: zano-runner
          # provenance: mode=max
          # sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "simple test: zano-runner (testnet)"
        run: |
          docker run --rm ${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-zano-runner-${{ steps.vars.outputs.sha_short }} --version

      - name: "build target: zanod-distroless (testnet)"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ matrix.zano-ref }}
            ZANO_CMAKE_ARGS="-D TESTNET=TRUE"
          tags: ${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-zanod-distroless,${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-zanod-distroless-${{ steps.vars.outputs.sha_short }}
          target: zanod-distroless
          # provenance: mode=max
          # sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "simple test: zanod-distroless (testnet)"
        run: |
          docker run --rm ${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-zanod-distroless-${{ steps.vars.outputs.sha_short }} --version

      - name: "build target: simplewallet-distroless (testnet)"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          build-args: |
            BUILD_WIDTH=${{ env.BUILD_WIDTH }}
            ZANO_REF=${{ matrix.zano-ref }}
            ZANO_CMAKE_ARGS="-D TESTNET=TRUE"
          tags: ${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-simplewallet-distroless,${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-simplewallet-distroless-${{ steps.vars.outputs.sha_short }}
          target: simplewallet-distroless
          # provenance: mode=max
          # sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "simple test: zanod-distroless (testnet)"
        run: |
          docker run --rm ${{ vars.DOCKERHUB_TESTNET_REPO }}:${{ matrix.zano-ref }}-simplewallet-distroless-${{ steps.vars.outputs.sha_short }} --version
